### ISSUE TITLE
Генерятся лишние импорты для @NonNull и @Nullable 

### ISSUE THREAD

**Issue by ayoanto** [fomin/oas-gen#18]
В java-котроллере генерятся импорты, которые не используются

Весь список импортов в сгенеренном контроллере

import javax.annotation.Nonnull; - не используется
import javax.annotation.Nullable; - не используется
import org.springframework.http.ResponseEntity;
import org.springframework.stereotype.Controller;
import org.springframework.web.bind.annotation.*;

**Comment by andrey-fomin** [comment]
В версиях 0.1.х это более не актуально
